name: cmake-example
base: core22
version: '0.1'
summary: An example snap for a CMake project
description: |
  Shows how to create a snap for an application that uses CMake for
  build and installation.

grade: devel
confinement: strict

apps:
  cmake-example:
    command: usr/bin/cmake-example

parts:
  cmake-example:
    plugin: cmake
    cmake-parameters: [-DCMAKE_INSTALL_PREFIX=/usr]
    source: .
